language: scala

sudo: false

scala:
  - 2.12.1
  - 2.11.8

jdk:
  - oraclejdk8

env:
  - TRAVIS_NODE_VERSION="6"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt ++$TRAVIS_SCALA_VERSION tests/test
