language: scala

sudo: false

scala:
  - 2.12.1
  - 2.11.8

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 7 # see scalacenter/scalajs-bundler#130
  - nvm use 7

script:
  - sbt ++$TRAVIS_SCALA_VERSION tests/test
