package co.technius.scalajs.mithril.tagsext

import co.technius.scalajs.mithril.VNode
import scalatags.generic

/*
 * Adapted from Scalatags by Li Haoyi, which is licensed under MIT License.
 */
trait SvgTags extends generic.SvgTags[VNode, VNode, VNode] with TagFactory {
  lazy val altGlyph = svgTag("altGlyph")
  lazy val altGlyphDef = svgTag("altGlyphDef")
  lazy val altGlyphItem = svgTag("altGlyphItem")
  lazy val animate = svgTag("animate")
  lazy val animateMotion = svgTag("animateMotion")
  lazy val animateTransform = svgTag("animateTransform")
  lazy val circle = svgTag("circle")
  lazy val clipPath = svgTag("clipPath")
  lazy val `color-profile` = svgTag("color-profile")
  lazy val cursor = svgTag("cursor")
  lazy val defs = svgTag("defs")
  lazy val desc = svgTag("desc")
  lazy val ellipse = svgTag("ellipse")
  lazy val feBlend = svgTag("feBlend")
  lazy val feColorMatrix = svgTag("feColorMatrix")
  lazy val feComponentTransfer = svgTag("feComponentTransfer")
  lazy val feComposite = svgTag("feComposite")
  lazy val feConvolveMatrix = svgTag("feConvolveMatrix")
  lazy val feDiffuseLighting = svgTag("feDiffuseLighting")
  lazy val feDisplacementMap = svgTag("feDisplacementMap")
  lazy val feDistantLighting = svgTag("feDistantLighting")
  lazy val feFlood = svgTag("feFlood")
  lazy val feFuncA = svgTag("feFuncA")
  lazy val feFuncB = svgTag("feFuncB")
  lazy val feFuncG = svgTag("feFuncG")
  lazy val feFuncR = svgTag("feFuncR")
  lazy val feGaussianBlur = svgTag("feGaussianBlur")
  lazy val feImage = svgTag("feImage")
  lazy val feMerge = svgTag("feMerge")
  lazy val feMergeNode = svgTag("feMergeNode")
  lazy val feMorphology = svgTag("feMorphology")
  lazy val feOffset = svgTag("feOffset")
  lazy val fePointLight = svgTag("fePointLight")
  lazy val feSpecularLighting = svgTag("feSpecularLighting")
  lazy val feSpotlight = svgTag("feSpotlight")
  lazy val feTile = svgTag("feTile")
  lazy val feTurbulance = svgTag("feTurbulance")
  lazy val filter = svgTag("filter")
  lazy val font = svgTag("font")
  lazy val `font-face` = svgTag("font-face")
  lazy val `font-face-format` = svgTag("font-face-format")
  lazy val `font-face-name` = svgTag("font-face-name")
  lazy val `font-face-src` = svgTag("font-face-src")
  lazy val `font-face-uri` = svgTag("font-face-uri")
  lazy val foreignObject = svgTag("foreignObject")
  lazy val g = svgTag("g")
  lazy val glyph = svgTag("glyph")
  lazy val glyphRef = svgTag("glyphRef")
  lazy val hkern = svgTag("hkern")
  lazy val image = svgTag("image")
  lazy val line = svgTag("line")
  lazy val linearGradient = svgTag("linearGradient")
  lazy val marker = svgTag("marker")
  lazy val mask = svgTag("mask")
  lazy val metadata = svgTag("metadata")
  lazy val `missing-glyph` = svgTag("missing-glyph")
  lazy val mpath = svgTag("mpath")
  lazy val path = svgTag("path")
  lazy val pattern = svgTag("pattern")
  lazy val polygon = svgTag("polygon")
  lazy val polyline = svgTag("polyline")
  lazy val radialGradient = svgTag("radialGradient")
  lazy val rect = svgTag("rect")
  lazy val set = svgTag("set")
  lazy val stop = svgTag("stop")
  lazy val svg = svgTag("svg")
  lazy val switch = svgTag("switch")
  lazy val symbol = svgTag("symbol")
  lazy val text = svgTag("text")
  lazy val textPath = svgTag("textPath")
  lazy val tref = svgTag("tref")
  lazy val tspan = svgTag("tspan")
  lazy val use = svgTag("use")
  lazy val view = svgTag("view")
  lazy val vkern = svgTag("vkern")
}
